CREATE PROC SP_SEARCH_BY
    @SEARCH_VALUE NVARCHAR(100),
    @SEARCH_ON_ID BIT = 1,
    @SEARCH_ON_FIRST_NAME BIT = 1,
    @SEARCH_ON_LAST_NAME BIT = 1,
    @SEARCH_ON_EMAIL BIT = 1,
    @SEARCH_ON_PHONE BIT = 0,
    @SEARCH_ON_GENDER BIT = 0,
AS
BEGIN
    SELECT *
    FROM NHANVIEN
    WHERE
        (@SEARCH_ON_ID = 1 AND ID LIKE '%' + @SEARCH_VALUE + '%')
        OR (@SEARCH_ON_FIRST_NAME = 1 AND HO LIKE '%' + @SEARCH_VALUE + '%')
        OR (@SEARCH_ON_LAST_NAME = 1 AND TEN LIKE '%' + @SEARCH_VALUE + '%')
        OR (@SEARCH_ON_EMAIL = 1 AND EMAIL LIKE '%' + @SEARCH_VALUE + '%')
        OR (@SEARCH_ON_PHONE = 1 AND SDT LIKE '%' + @SEARCH_VALUE + '%')
END
