CREATE PROC SP_CHECK_EXIST_LOGIN
  @LOGIN_NAME VARCHAR(50)
AS
BEGIN
	DECLARE @SID INT = NULL;

	--* Get 'sid' corresponding with MANV as UserName in DB.
	SELECT TOP 1 @SID = SYS.SYSUSERS.sid FROM SYS.SYSUSERS WHERE SYS.SYSUSERS.name = @MANV;

	--* Check if LoginName is existing in Server by 'sid'.
	IF @SID IS NOT NULL
	BEGIN
		IF EXISTS(SELECT 1 FROM SYS.SYSLOGINS WHERE sid = @SID)
			RETURN 1;
	END

	RETURN 0;
END