CREATE PROCEDURE SP_CHECK_EXIST_STORAGE_ID
	@MAKHO NCHAR(4)
AS
BEGIN
	-- SINCE THE SITE 3 IS FOR CHECKING UP THE STORAGE AND EMPLOYEE INFORMATION.
	-- THEREFORE THE BEST IS THAT WE CHECK FOR THE STORAGE ID IN THE SITE 3.
	IF (EXIST(SELECT 1 FROM LINK0.QLVT_DATHANG.DBO.KHO AS K
				WHERE K.MAKHO = @MAKHO))
		return 1;
	return 0;
END