CREATE PROC SP_CHECK_EXIST_LOGIN
  @LOGIN_NAME VARCHAR(50)
AS
BEGIN
	DECLARE @RET INT
	EXEC @RET = SP_ADDLOGIN @LOGIN_NAME, 'random-password', 'QLVT_DATHANG'
	IF (@RET = 1)
		RETURN 1
	ELSE
		RETURN 0
END