CREATE PROCEDURE SP_CHECK_EXIST_SUPPLY_ID
    @MAVT NCHAR(4)
AS
BEGIN
	-- CHECK THE SUPPLY ID EXIST IN CURENT SITE
    IF EXISTS(SELECT 1 FROM Vattu AS VT WHERE VT.MAVT = @MAVT)
			RETURN 1;
	-- CHECK THE SUPPLY ID EXIST IN OTHER SITE
	ELSE IF EXISTS(SELECT 1 FROM LINK1.QLVT_DATHANG.DBO.Vattu AS VT WHERE VT.MAVT = @MAVT)
			RETURN 1;
	RETURN 0;
END