CREATE PROC SP_CHECK_EXIST_LOGIN
  @LOGIN_NAME VARCHAR(50)
AS
BEGIN
  DECLARE @RET INT
  EXEC @RET = SP_ADDLOGIN @LOGIN_NAME, 'random-password', 'QLVT_DATHANG'
  IF (@RET = 1)
  BEGIN
    RAISERROR('Duplicated login name', 16,1)
    RETURN 0
  END

  RETURN 1
END