CREATE PROCEDURE SP_CHECK_EXIST_CMND
    @MANV INT,
    @CMND NVARCHAR(10)
AS
BEGIN
    SELECT MANV
    FROM LINK0.QLVT_DATHANG.DBO.NHANVIEN
    WHERE
        TRANGTHAIXOA = 0 AND
        (CMND = @CMND OR MANV = @MANV)
END