SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SP_DELETE_EMPLOYEE
	@MANV INT
AS
BEGIN
	SET NOCOUNT ON;
	If EXISTS(SELECT 1 FROM NhanVien WHERE MANV = @MANV AND TrangThaiXoa = 0)
	BEGIN
		UPDATE NhanVien SET TrangThaiXoa = 1 WHERE MANV = @MANV;
		
	END;
	Else
		THROW 51000, 'Employee info is invalid', 1;
END
GO
