USE [QLVT_DATHANG]
GO
/****** Object:  StoredProcedure [dbo].[SP_UPDATE_SUPPLIES_EXPORTATION_DETAIL]    Script Date: 6/19/2024 10:48:56 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Le Van Dung
-- Create date: 19/6/2024
-- =============================================
CREATE PROCEDURE [dbo].[SP_FIND_TICKETS_FOR_DETAIL_SUPPLIES_REPORT]
	@LOAIPHIEU NVARCHAR(10), @FROM_DATE DATE, @TO_DATE DATE
AS
BEGIN
	IF (@LOAIPHIEU = 'NHAP') BEGIN
		SELECT TENVT,
			THANG=CONCAT(MONTH(PN.NGAY), '-', YEAR(PN.NGAY)),
			TONGSOLUONG=SUM(SOLUONG),
			TONGTRIGIA=SUM(SOLUONG*DONGIA)
		FROM PhieuNhap AS PN
		INNER JOIN (SELECT MAPN, TENVT, SOLUONG, DONGIA FROM CTPN INNER JOIN Vattu ON CTPN.MAVT=Vattu.MAVT) AS _CTPN
		ON PN.MAPN=_CTPN.MAPN
		GROUP BY CONCAT(MONTH(PN.NGAY), '-', YEAR(PN.NGAY)), TENVT;
	END;
	ELSE IF (@LOAIPHIEU = 'XUAT') BEGIN
		SELECT TENVT,
			THANG=CONCAT(MONTH(PX.NGAY), '-', YEAR(PX.NGAY)),
			TONGSOLUONG=SUM(SOLUONG),
			TONGTRIGIA=SUM(SOLUONG*DONGIA)
		FROM PhieuXuat AS PX
		INNER JOIN (SELECT MAPX, TENVT, SOLUONG, DONGIA FROM CTPX INNER JOIN Vattu ON CTPX.MAVT=Vattu.MAVT) AS _CTPX
		ON PX.MAPX=_CTPX.MAPX
		GROUP BY CONCAT(MONTH(PX.NGAY), '-', YEAR(PX.NGAY)), TENVT;
	END;
	ELSE THROW 51000, 'Invalid LOAIPHIEU', 1;
END

