CREATE PROC	SP_FETCH_ROLE_NAME_BY_EMPLOYEE_ID
	@EMPLOYEE_ID INT,
	@ROLE_NAME NVARCHAR(8) OUTPUT
AS
BEGIN
	DECLARE @RESULT NVARCHAR(8);

	SELECT
		@RESULT = DB_PRINC.NAME
	FROM
		SYS.DATABASE_PRINCIPALS AS DB_PRINC,
		(SELECT
				DB_PRINC.NAME AS USERNAME,
				DBRM.MEMBER_PRINCIPAL_ID AS MAPPING_MEMBER_ID,
				DBRM.ROLE_PRINCIPAL_ID AS MAPPING_ROLE_ID
			FROM
				SYS.DATABASE_ROLE_MEMBERS AS DBRM,
				(SELECT DB_PRINC.PRINCIPAL_ID, DB_PRINC.NAME 
					FROM SYS.DATABASE_PRINCIPALS AS DB_PRINC 
					WHERE DB_PRINC.NAME = @EMPLOYEE_ID) AS DB_PRINC
			WHERE
				DB_PRINC.PRINCIPAL_ID = DBRM.MEMBER_PRINCIPAL_ID) AS ROLE_MAPPING
	WHERE
		ROLE_MAPPING.MAPPING_ROLE_ID = DB_PRINC.PRINCIPAL_ID

	SET @ROLE_NAME = @RESULT;
END