CREATE PROCEDURE SP_LIST_ALL_SUPLLIES
AS
BEGIN
    SELECT
        VT.MAVT AS MAVT,
        VT.TENVT AS TEN_VAT_TU,
        VT.SOLUONGTON AS SO_LUONG_TON,
        VT.DVT AS DON_VI_TINH
    FROM VATTU AS VT
    ORDER BY VT.TENVT
END