CREATE PROCEDURE SP_REPORT_OF_PERCENTAGE_OF_IMPORT_AND_EXPORT
    @ROLE NVARCHAR(8),
    @FROM_DATE DATETIME,
    @TO_DATE DATETIME
AS
BEGIN
    DECLARE @TOTAL_IMPORT INT;
    DECLARE @TOTAL_EXPORT INT;
    
    -- CALCULATE TOTAL IMPORT
    SELECT
        PN.MAPN AS MAPN,
        PN.NGAY AS NGAY,
        @TOTAL_IMPORT = SUM(CTPN.SOLUONG * CTPN.DONGIA)
    INTO #TEMP_IMPORT
    FROM (SELECT * FROM PhieuNhap WHERE NGAY BETWEEN @FROM_DATE AND @TO_DATE) AS PN
    INNER JOIN CTPN AS CTPN ON PN.MAPN = CTPN.MAPN
    GROUP BY PN.MAPN, PN.NGAY

    -- CALCULATE TOTAL EXPORT
    SELECT
        PX.MAPX AS MAPX,
        PX.NGAY AS NGAY,
        @TOTAL_EXPORT = SUM(CTPX.SOLUONG * CTPX.DONGIA)
    INTO #TEMP_EXPORT
    FROM (SELECT * FROM PhieuXuat WHERE NGAY BETWEEN @FROM_DATE AND @TO_DATE) AS PX
    INNER JOIN CTPX AS CTPX ON PX.MAPX = CTPX.MAPX
    GROUP BY PX.MAPX, PX.NGAY

    SELECT 
        ISNULL(TOTAL_IMPORT_DETAILS.NGAY, TOTAL_EXPORT_DETAILS.NGAY) AS NGAY,
        ISNULL(TOTAL_IMPORT_DETAILS.NHAP, 0) AS NHAP,
        ISNULL(TOTAL_IMPORT_DETAILS.TI_LE_NHAP, 0) AS TI_LE_NHAP,
        ISNULL(TOTAL_EXPORT_DETAILS.NHAP, 0) AS XUAT,
        ISNULL(TOTAL_EXPORT_DETAILS.TI_LE_NHAP, 0) AS TI_LE_XUAT
    FROM (
        SELECT
            #TEMP_IMPORT.NGAY AS NGAY,
            SUM(CTPN.SOLUONG * CTPN.DONGIA) AS NHAP,
            SUM(CTPN.SOLUONG * CTPN.DONGIA) * 100 / @TOTAL_IMPORT AS TI_LE_NHAP
        FROM #TEMP_IMPORT AS PN
        INNER JOIN CTPN AS CTPN
            ON #TEMP_IMPORT.MAPN = CTPN.MAPN) AS TOTAL_IMPORT_DETAILS
    FULL OUTER JOIN (
        SELECT
            #TEMP_EXPORT.NGAY AS NGAY,
            SUM(CTPX.SOLUONG * CTPX.DONGIA) AS NHAP,
            SUM(CTPX.SOLUONG * CTPX.DONGIA) * 100 / @TOTAL_EXPORT AS TI_LE_NHAP
        FROM #TEMP_EXPORT AS PX
        INNER JOIN CTPX AS CTPX
            ON #TEMP_EXPORT.MAPX = CTPX.MAPX) AS TOTAL_EXPORT_DETAILS
    ON TOTAL_IMPORT_DETAILS.NGAY = TOTAL_EXPORT_DETAILS.NGAY
END