CREATE PROCEDURE [dbo].[SP_REPORT_EMPLOYEE_WORKING_STATUS]
    @MANV INT, @FROM_DATE DATE, @TO_DATE DATE
AS
BEGIN
    SELECT NGAY, PN.MAPN, LOAIPHIEU='NHAP', HOTENKH='NULL', TENVT, SOLUONG, DONGIA, TRIGIA=SOLUONG*DONGIA INTO #DSPN
	FROM (SELECT NGAY, MAPN FROM PhieuNhap WHERE MANV = @MANV AND NGAY BETWEEN @FROM_DATE AND @TO_DATE) AS PN
	INNER JOIN (
		SELECT MAPN, TENVT, SOLUONG, DONGIA FROM CTPN INNER JOIN VATTU ON VATTU.MAVT=CTPN.MAVT
	) AS THONGTIN_VATTU ON THONGTIN_VATTU.MAPN=PN.MAPN;

	SELECT NGAY, PX.MAPX, LOAIPHIEU='XUAT', HOTENKH, TENVT, SOLUONG, DONGIA, TRIGIA=SOLUONG*DONGIA INTO #DSPX
	FROM (SELECT NGAY, MAPX, HOTENKH FROM PhieuXuat WHERE MANV = @MANV AND NGAY BETWEEN @FROM_DATE AND @TO_DATE) AS PX
	INNER JOIN (
		SELECT MAPX, TENVT, SOLUONG, DONGIA FROM CTPX INNER JOIN VATTU ON VATTU.MAVT=CTPX.MAVT
	) AS THONGTIN_VATTU ON THONGTIN_VATTU.MAPX=PX.MAPX;

	SELECT * FROM #DSPN
	UNION
	SELECT * FROM #DSPX
	ORDER BY #DSPN.NGAY
END