CREATE PROCEDURE SP_REPORT_OF_PERCENTAGE_OF_IMPORT_AND_EXPORT
    @FROM_DATE DATETIME,
    @TO_DATE DATETIME
AS
BEGIN
    -- TAKING ALL THE IMPORT AND IMPORT DETAIL WITHIN THE DATE RANGE
    SELECT
        PN.NGAY AS NGAY,
        CTPN.SOLUONG AS SOLUONG,
        CTPN.DONGIA AS DONGIA
    INTO #TEMP_IMPORT
    FROM (SELECT * FROM PhieuNhap WHERE NGAY BETWEEN @FROM_DATE AND @TO_DATE) AS PN
    INNER JOIN CTPN AS CTPN ON PN.MAPN = CTPN.MAPN

    -- TAKING ALL THE EXPORT AND EXPORT DETAIL WITHIN THE DATE RANGE
    SELECT
        PX.NGAY AS NGAY,
        CTPX.SOLUONG AS SOLUONG,
        CTPX.DONGIA AS DONGIA
    INTO #TEMP_EXPORT
    FROM (SELECT * FROM PhieuXuat WHERE NGAY BETWEEN @FROM_DATE AND @TO_DATE) AS PX
    INNER JOIN CTPX AS CTPX ON PX.MAPX = CTPX.MAPX

    -- CALCULATING THE TOTAL IMPORT AND EXPORT
    SELECT 
        ISNULL(TOTAL_IMPORT_DETAILS.NGAY, TOTAL_EXPORT_DETAILS.NGAY) AS NGAY,
        ISNULL(TOTAL_IMPORT_DETAILS.NHAP, 0) AS NHAP,
        ISNULL(TOTAL_IMPORT_DETAILS.TI_LE_NHAP, 0) AS TI_LE_NHAP,
        ISNULL(TOTAL_EXPORT_DETAILS.NHAP, 0) AS XUAT,
        ISNULL(TOTAL_EXPORT_DETAILS.TI_LE_NHAP, 0) AS TI_LE_XUAT
    FROM (
        SELECT
            PN.NGAY AS NGAY,
            SUM(PN.SOLUONG * PN.DONGIA) AS NHAP,
            TI_LE_NHAP = SUM(PN.SOLUONG * PN.DONGIA) * 100 / (SELECT SUM(SOLUONG * DONGIA) FROM #TEMP_IMPORT)
        FROM #TEMP_IMPORT AS PN) AS TOTAL_IMPORT_DETAILS
    FULL OUTER JOIN (
        SELECT
            #TEMP_EXPORT.NGAY AS NGAY,
            SUM(PX.SOLUONG * PX.DONGIA) AS NHAP,
            TI_LE_NHAP = SUM(PX.SOLUONG * PX.DONGIA) * 100 / (SELECT SUM(SOLUONG * DONGIA) FROM #TEMP_EXPORT)
        FROM #TEMP_EXPORT AS PX) AS TOTAL_EXPORT_DETAILS
    ON TOTAL_IMPORT_DETAILS.NGAY = TOTAL_EXPORT_DETAILS.NGAY
END
