CREATE PROC SP_SUPPLY_TREND
AS
BEGIN
	SELECT VATTU.TENVT, TONG_NHAP.TONG, VATTU.MAVT
	INTO #TEMP_NHAP
	FROM VATTU
	INNER JOIN (SELECT MAVT, TONG = SUM(SOLUONG) FROM CTPN GROUP BY MAVT) AS TONG_NHAP
	ON TONG_NHAP.MAVT = VATTU.MAVT;

	SELECT VATTU.TENVT, TONG_XUAT.TONG, VATTU.MAVT
	INTO #TEMP_XUAT
	FROM VATTU
	INNER JOIN (SELECT MAVT, TONG = SUM(SOLUONG) FROM CTPX GROUP BY MAVT) AS TONG_XUAT
	ON TONG_XUAT.MAVT = VATTU.MAVT;

	SELECT 
		#TEMP_NHAP.TENVT,
		ISNULL(#TEMP_NHAP.TONG, 0) AS TONG_NHAP,
		ISNULL(#TEMP_XUAT.TONG, 0) AS TONG_XUAT
	FROM #TEMP_NHAP
	FULL OUTER JOIN #TEMP_XUAT
	ON #TEMP_NHAP.MAVT = #TEMP_XUAT.MAVT;

	DROP TABLE #TEMP_NHAP
	DROP TABLE #TEMP_XUAT
END