CREATE VIEW VIEW_GET_EMPLOYEE_LIST
AS
	SELECT
		MANV,
		CONCAT(HO, ' ', TEN, ' - ', MANV) as HOTEN
	FROM NHANVIEN 
	WHERE TrangThaiXoa = 0
		AND NOT EXISTS(
			SELECT SUSER_SNAME(sid) FROM sys.sysusers 
			WHERE name = CAST(MANV AS NVARCHAR))